const T=[];let pass=0,fail=0;
const ok=(n,c,x)=>{c?pass++:fail++;T.push((c?'PASS  ':'FAIL  ')+n+(x!==undefined&&x!==''?'   → '+x:''))};
const w=ms=>new Promise(r=>setTimeout(r,ms));
const sheet=()=>document.getElementById('verifyContent');
(async()=>{
 for(let i=0;i<80&&document.querySelectorAll('.row').length<3;i++)await w(100);
 const W0=window.__W__.length;
 T.push('──── 2 · SECOND CHECK, NOT INDEPENDENT CHECK ────');
 openRecord('56a859b5-aaaa'); await w(200);
 const t=sheet().innerText;
 ok('title reads Second Check', sheet().querySelector('.vfy-t').textContent==='Second Check');
 ok('"Independent Check" appears nowhere on the page', !/independent check/i.test(document.body.innerText));
 ok('one instruction kept', /Have another team member check the allergy preparation\./.test(t));
 ok('provenance kept: display, not person', /records the display, not the person\./.test(t));
 ok('row button aria no longer says independent', [...document.querySelectorAll('.r-act--nav')].every(b=>!/independent/i.test(b.getAttribute('aria-label'))));
 ok('old unauthenticated claim is gone', !/not signed in/i.test(document.body.innerText));
 ok('provenance falls back to "this venue" before the venue read', /Kitchen Display · this venue — records the display, not the person\./.test(t));
 ok('no personal-identity or different-person claim', !/(verified|checked|confirmed) by (another|a different)|independently/i.test(sheet().innerText));
 await window.__realLoadVenue(); await w(250);
 ok('venue name comes from the device-credential read', /Kitchen Display · Happy Bistro — records the display, not the person\./.test(sheet().innerText), vdVenueName);
 ok('venue name not set from the query string', !/venue=/.test(location.search));
 T.push('──── 4b · REHEARSAL HIERARCHY ────');
 const hd=sheet().querySelector('.vfy-hd'), reh=hd.querySelector('.vfy-reh'), ttl=hd.querySelector('.vfy-t');
 ok('rehearsal marker present with full wording', !!reh && /REHEARSAL · NOT A GUEST/.test(reh.textContent));
 ok('rehearsal sits ABOVE the title', !!reh && reh.getBoundingClientRect().bottom<=ttl.getBoundingClientRect().top+1);
 ok('rehearsal is a compact status, smaller than the title', parseFloat(getComputedStyle(reh).fontSize)<parseFloat(getComputedStyle(ttl).fontSize), getComputedStyle(reh).fontSize+' < '+getComputedStyle(ttl).fontSize);
 ok('rehearsal still boxed, bold, purple', getComputedStyle(reh).borderTopStyle==='solid' && +getComputedStyle(reh).fontWeight>=800 && getComputedStyle(reh).color==='rgb(201, 173, 255)');
 ok('big lockout-style rehearsal block no longer on the sheet', !sheet().querySelector('.lockout-reh'));
 const order=['.vfy-reh','.vfy-t','.vfy-tbl','.vfy-guest','.vfy-al'].map(q=>sheet().querySelector(q).getBoundingClientRect().top);
 ok('order: REHEARSAL → Second Check → P4 · Terrace → Tom → allergens', order.every((y,i)=>i===0||y>order[i-1]), order.map(Math.round).join(' < '));
 ok('service point line reads P4 · Terrace', sheet().querySelector('.vfy-tbl').textContent==='P4 · Terrace', sheet().querySelector('.vfy-tbl').textContent);
 ok('close button still reachable in the header', !!hd.querySelector('.vfy-x'));
 T.push('──── 4 · ACTION COLOUR ────');
 const b=sheet().querySelector('.vfy-go'), cs=getComputedStyle(b), ok_=getComputedStyle(document.documentElement).getPropertyValue('--ok').trim();
 ok('sheet action still the hold to record the second check', /Hold to Record Second Check/.test(b.textContent));
 ok('action is not the green success class', !b.classList.contains('green') && b.classList.contains('act'));
 ok('action background is not the --ok success colour', cs.backgroundColor!=='rgb(16, 185, 129)', cs.backgroundColor);
 ok('action uses the neutral action surface (--s2)', cs.backgroundColor==='rgb(26, 37, 53)', cs.backgroundColor);
 const fill=getComputedStyle(b.querySelector('.hold-fill')).backgroundColor;
 ok('hold fill is light enough to see on the dark button', /rgba\(226, 232, 240/.test(fill), fill);
 ok('progress rail still shows Second Check stage (not yet done)', /Second Check/.test(sheet().querySelector('.prog').innerText));
 ok('red still carries anaphylaxis severity', getComputedStyle(sheet().querySelector('.vfy-sev.an')).color==='rgb(239, 68, 68)');
 ok('rehearsal marker still present', /REHEARSAL/.test(t));
 T.push('──── 3 · REFERENCE-LIST LANGUAGE ────');
 closeRecord(); await w(100); openRecord('ba65384b-cccc'); await w(200);
 const a=sheet().innerText;
 ok('Peanut heading is human', /PEANUT — CHECK INGREDIENTS/.test(a), (a.match(/PEANUT[^\n]*/)||[''])[0]);
 ok('supporting copy', /No reference list is available\. Confirm ingredients before preparation\./.test(a));
 ok('no "derivative list" wording on the sheet', !/derivative list/i.test(a));
 ok('Sesame still renders its Avoid all list', /AVOID ALL — SESAME/.test(a));
 ok('A (unacked) action still Confirm Received, red', /Hold to Confirm Allergy Received/.test(a) && sheet().querySelector('.vfy-go').classList.contains('red'));
 closeRecord(); await w(100);
 showLockout('ba65384b-cccc'); await w(100);
 const l=document.getElementById('lockoutContent').innerText;
 ok('lockout uses the same reference-list language', /PEANUT — CHECK INGREDIENTS/i.test(l) && /No reference list is available/.test(l) && !/derivative list/i.test(l));
 document.getElementById('lockout').classList.remove('on');
 T.push('──── 5 · ACTION-RELATIVE ELAPSED TIME ────');
 const el=()=>(sheet().innerText.match(/[^\n]* waiting [^\n]*/)||[''])[0];
 const exp=(since)=>fmtTimer(since);
 openRecord('56a859b5-aaaa'); await w(200);
 const B=cards['56a859b5-aaaa'];
 ok('B (awaiting Second Check) timed from protocol_confirmed_at', el()==='Second Check waiting '+exp(B.protocol_confirmed_at), el()+' | created_at would be '+exp(B.created_at));
 ok('no bare "Waiting <age>" from created_at', !/^Waiting /m.test(sheet().innerText));
 await w(1200); ok('the 1s tick keeps the same basis', el()==='Second Check waiting '+exp(B.protocol_confirmed_at), el());
 closeRecord(); await w(100);
 openRecord('ba65384b-cccc'); await w(200);
 const A=cards['ba65384b-cccc'];
 ok('A (awaiting Received) timed from created_at', el()==='Confirm Received waiting '+exp(A.created_at), el());
 closeRecord(); await w(100);
 const base={severity:'anaphylaxis',created_at:'2026-01-01T00:00:00Z'};
 const s1=owedStep(Object.assign({},base,{kitchen_ack_at:'2026-01-02T00:00:00Z'}));
 ok('awaiting Prep → kitchen_ack_at', s1.label==='Prep Confirmation'&&s1.since==='2026-01-02T00:00:00Z');
 const s2=owedStep(Object.assign({},base,{kitchen_ack_at:'2026-01-02T00:00:00Z',protocol_confirmed_at:'2026-01-03T00:00:00Z',verified_at:'2026-01-04T00:00:00Z'}));
 ok('awaiting Served → verified_at', s2.label==='Mark Served'&&s2.since==='2026-01-04T00:00:00Z');
 const s3=owedStep({severity:'severe',created_at:'2026-01-01T00:00:00Z',kitchen_ack_at:'2026-01-02T00:00:00Z'});
 ok('non-anaphylaxis skips prep: Second Check from kitchen_ack_at', s3.label==='Second Check'&&s3.since==='2026-01-02T00:00:00Z');
 ok('served → no owed step', owedStep(Object.assign({},base,{served_at:'2026-01-05T00:00:00Z'}))===null);
 ok('escalation clock untouched (checkEscalations still keyed off created_at/ack)', /created_at/.test(checkEscalations.toString()) && !/owedStep/.test(checkEscalations.toString()));
 ok('probe performed zero writes', window.__W__.length===W0, window.__W__.length-W0);
 T.push(''); T.push(fail===0?('ALL '+pass+' CHECKS PASS'):(pass+' pass, '+fail+' FAIL'));
 try{await fetch('/__results',{method:'POST',body:T.join('\n')})}catch(e){}
})();
