const T=[];let pass=0,fail=0;
const ok=(n,c,x)=>{c?pass++:fail++;T.push((c?'PASS  ':'FAIL  ')+n+(x!==undefined&&x!==''?'   → '+x:''))};
const w=ms=>new Promise(r=>setTimeout(r,ms));
const sheet=()=>document.getElementById('verifyContent');
(async()=>{
 for(let i=0;i<80&&document.querySelectorAll('.row').length<3;i++)await w(100);
 const W0=window.__W__.length;
 T.push('──── 2 · SECOND CHECK, NOT INDEPENDENT CHECK ────');
 openRecord('56a859b5-aaaa'); await w(200);
 const t=sheet().innerText;
 ok('title reads Second Check', sheet().querySelector('.vfy-t').textContent==='Second Check');
 ok('"Independent Check" appears nowhere on the page', !/independent check/i.test(document.body.innerText));
 ok('instruction kept', /Another team member should check the allergy preparation/.test(t));
 ok('identity disclosure kept', /does not prove who carried it out/.test(t));
 ok('row button aria no longer says independent', [...document.querySelectorAll('.r-act--nav')].every(b=>!/independent/i.test(b.getAttribute('aria-label'))));
 T.push('──── 4 · ACTION COLOUR ────');
 const b=sheet().querySelector('.vfy-go'), cs=getComputedStyle(b), ok_=getComputedStyle(document.documentElement).getPropertyValue('--ok').trim();
 ok('sheet action still the hold to record the second check', /Hold to Record Second Check/.test(b.textContent));
 ok('action is not the green success class', !b.classList.contains('green') && b.classList.contains('act'));
 ok('action background is not the --ok success colour', cs.backgroundColor!=='rgb(16, 185, 129)', cs.backgroundColor);
 ok('action uses the neutral action surface (--s2)', cs.backgroundColor==='rgb(26, 37, 53)', cs.backgroundColor);
 const fill=getComputedStyle(b.querySelector('.hold-fill')).backgroundColor;
 ok('hold fill is light enough to see on the dark button', /rgba\(226, 232, 240/.test(fill), fill);
 ok('progress rail still shows Second Check stage (not yet done)', /Second Check/.test(sheet().querySelector('.prog').innerText));
 ok('red still carries anaphylaxis severity', getComputedStyle(sheet().querySelector('.vfy-sev.an')).color==='rgb(239, 68, 68)');
 ok('rehearsal marker still present', /REHEARSAL/.test(t));
 T.push('──── 3 · REFERENCE-LIST LANGUAGE ────');
 closeRecord(); await w(100); openRecord('ba65384b-cccc'); await w(200);
 const a=sheet().innerText;
 ok('Peanut heading is human', /PEANUT — CHECK INGREDIENTS/.test(a), (a.match(/PEANUT[^\n]*/)||[''])[0]);
 ok('supporting copy', /No reference list is available\. Confirm ingredients before preparation\./.test(a));
 ok('no "derivative list" wording on the sheet', !/derivative list/i.test(a));
 ok('Sesame still renders its Avoid all list', /AVOID ALL — SESAME/.test(a));
 ok('A (unacked) action still Confirm Received, red', /Hold to Confirm Allergy Received/.test(a) && sheet().querySelector('.vfy-go').classList.contains('red'));
 closeRecord(); await w(100);
 showLockout('ba65384b-cccc'); await w(100);
 const l=document.getElementById('lockoutContent').innerText;
 ok('lockout uses the same reference-list language', /PEANUT — CHECK INGREDIENTS/i.test(l) && /No reference list is available/.test(l) && !/derivative list/i.test(l));
 document.getElementById('lockout').classList.remove('on');
 T.push('──── 5 · AGE UNCHANGED (report only) ────');
 openRecord('56a859b5-aaaa'); await w(200);
 ok('Waiting still derived from created_at (unchanged this batch)', /Waiting \d+d/.test(sheet().innerText), (sheet().innerText.match(/Waiting [^\n]*/)||[''])[0]);
 closeRecord();
 ok('probe performed zero writes', window.__W__.length===W0, window.__W__.length-W0);
 T.push(''); T.push(fail===0?('ALL '+pass+' CHECKS PASS'):(pass+' pass, '+fail+' FAIL'));
 try{await fetch('/__results',{method:'POST',body:T.join('\n')})}catch(e){}
})();
