#!/usr/bin/env node
// Builds the Spanish review material from the SAME sources the board uses — the I18N catalog in
// index.html and review-meta.json — so neither the Markdown nor the review page can drift from
// the code.   node tests/i18n/build-review.js [out.html]
'use strict';
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..', '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const I18N = eval('(' + html.slice(html.indexOf('var I18N={'), html.indexOf('var KITCHEN_LOCALES')).replace(/^var I18N=/, '').replace(/;\s*$/, '') + ')');
const META = JSON.parse(fs.readFileSync(path.join(__dirname, 'review-meta.json'), 'utf8'));
const GROUPS = [['safety', 'Safety and workflow'], ['actions', 'Actions'], ['status', 'Status and progress'],
  ['rehearsal', 'Rehearsal'], ['errors', 'Errors and offline'], ['general', 'Navigation and general']];
const UNRESOLVED = ['chip.cross_contact'];
const rows = Object.keys(I18N.en).map(k => ({ key: k, en: I18N.en[k], es: I18N.es[k], zh: I18N['zh-CN'][k], ...META[k] }));
// Order: the highest-risk operational terms (in the agreed order), then every other string flagged
// in either language, then the rest by area.
const priority = rows.filter(r => r.priority).sort((a, b) => a.priority - b.priority);
const otherFlagged = rows.filter(r => !r.priority && (r.concern || r.zh_concern));
const flagged = [...priority, ...otherFlagged];
const UNTRANSLATED = [
  ['Allergen names', 'Fish, Tree Nuts, Sesame, Peanut', 'Stored exactly as the guest chose them. Translating them needs the canonical allergen vocabulary, which does not exist yet.'],
  ['Reference lists (Avoid all)', 'Cod · Salmon · Worcestershire · Caesar dressing', 'Safety content. Each list needs its own reviewed Spanish and Chinese version, not a word-by-word translation.'],
  ['Guest notes', '"I get sick"', 'The guest’s own words, shown verbatim and labelled “sin traducir” / “未翻译”. Never machine-translated.'],
  ['Guest name', 'Tom', 'Data.'],
  ['Table and service point', 'P4 · Terrace', 'The venue’s own labels.'],
  ['Venue and display names', 'Happy Bistro · Kitchen Display', 'Set by the venue. “Kitchen Display” is also what the database records as the display that acted.'],
];

// ── Markdown (repo) ────────────────────────────────────────────────────────────────────────────
const cell = s => (s == null || s === '' ? '—' : String(s).replace(/\|/g, '\\|').replace(/\n/g, ' '));
let md = '# Kitchen strings — EN / ES / ZH-CN review matrix (DRAFT, not approved for pilot)\n\n';
md += `Generated by \`tests/i18n/build-review.js\` from the catalog in \`index.html\` and \`review-meta.json\`. ${rows.length} strings × 3 languages; ${rows.filter(r => r.concern).length} Spanish and ${rows.filter(r => r.zh_concern).length} Chinese flags; ${priority.length} highest-risk terms first.\n\n`;
md += '**Neither Spanish (written for Mexican / U.S. kitchens) nor Simplified Chinese is approved for pilot until a native speaker who knows U.S. restaurant kitchens has reviewed it.** Decisions are collected on the review page; this file is the reference copy.\n\n';
md += '## Intentionally untranslated (do not translate in this pass)\n\n| Data | Example | Why |\n|---|---|---|\n' + UNTRANSLATED.map(u => `| ${u.join(' | ')} |`).join('\n') + '\n\n';
const concern = r => [(UNRESOLVED.includes(r.key) ? 'UNRESOLVED — requires approval.' : ''),
  r.concern ? 'ES: ' + r.concern : '', r.zh_concern ? 'ZH: ' + r.zh_concern : ''].filter(Boolean).join(' ');
const table = list => '| English | Spanish | Simplified Chinese | Where shown | Operational meaning | Safety / translation concern | ES approved | ZH-CN approved |\n|---|---|---|---|---|---|---|---|\n'
  + list.map(r => `| ${cell(r.en)} | ${cell(r.es)} | ${cell(r.zh)} | ${cell(r.where)} | ${cell(r.meaning)} | ${cell(concern(r))} | | |`).join('\n') + '\n\n';
md += `## Highest-risk operational terms (${priority.length})\n\n` + table(priority);
md += `## Other flagged strings (${otherFlagged.length})\n\n` + table(otherFlagged);
for (const [g, label] of GROUPS) {
  const list = rows.filter(r => !r.priority && !r.concern && !r.zh_concern && r.group === g);
  if (list.length) md += `## ${label} (${list.length})\n\n` + table(list);
}
fs.writeFileSync(path.join(__dirname, 'KITCHEN_STRINGS_EN_ES_ZH.md'), md);

// ── Review page ────────────────────────────────────────────────────────────────────────────────
const out = process.argv[2];
if (out) {
  const tpl = fs.readFileSync(path.join(__dirname, 'review-page.template.html'), 'utf8');
  const data = { rows, priority: priority.map(r => r.key), otherFlagged: otherFlagged.map(r => r.key), unresolved: UNRESOLVED, groups: GROUPS, untranslated: UNTRANSLATED,
    generated: new Date().toISOString().slice(0, 10) };
  fs.writeFileSync(out, tpl.replace('/*__DATA__*/null', JSON.stringify(data).replace(/</g, '\\u003c')));
}
console.log(`review material: ${rows.length} strings; ${priority.length} highest-risk, ${otherFlagged.length} other flagged${out ? '; page → ' + out : ''}`);
