#!/usr/bin/env node
// Builds the Spanish review material from the SAME sources the board uses — the I18N catalog in
// index.html and review-meta.json — so neither the Markdown nor the review page can drift from
// the code.   node tests/i18n/build-review.js [out.html]
'use strict';
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..', '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const I18N = eval('(' + html.slice(html.indexOf('var I18N={'), html.indexOf('var KITCHEN_LOCALES')).replace(/^var I18N=/, '').replace(/;\s*$/, '') + ')');
const META = JSON.parse(fs.readFileSync(path.join(__dirname, 'review-meta.json'), 'utf8'));
const GROUPS = [['safety', 'Safety and workflow'], ['actions', 'Actions'], ['status', 'Status and progress'],
  ['rehearsal', 'Rehearsal'], ['errors', 'Errors and offline'], ['general', 'Navigation and general']];
const UNRESOLVED = ['chip.cross_contact'];
const rows = Object.keys(I18N.en).map(k => ({ key: k, en: I18N.en[k], es: I18N.es[k], ...META[k] }));
const flagged = rows.filter(r => r.concern).sort((a, b) => (UNRESOLVED.includes(b.key) - UNRESOLVED.includes(a.key)));
const UNTRANSLATED = [
  ['Allergen names', 'Fish, Tree Nuts, Sesame, Peanut', 'Stored exactly as the guest chose them. Translating them needs the canonical allergen vocabulary, which does not exist yet.'],
  ['Reference lists (Avoid all)', 'Cod · Salmon · Worcestershire · Caesar dressing', 'Safety content. Each list needs its own reviewed Spanish version, not a word-by-word translation.'],
  ['Guest notes', '"I get sick"', 'The guest’s own words, shown verbatim and labelled “sin traducir”. Never machine-translated.'],
  ['Guest name', 'Tom', 'Data.'],
  ['Table and service point', 'P4 · Terrace', 'The venue’s own labels.'],
  ['Venue and display names', 'Happy Bistro · Kitchen Display', 'Set by the venue. “Kitchen Display” is also what the database records as the display that acted.'],
];

// ── Markdown (repo) ────────────────────────────────────────────────────────────────────────────
const cell = s => (s == null || s === '' ? '—' : String(s).replace(/\|/g, '\\|').replace(/\n/g, ' '));
let md = '# Kitchen Spanish — review sheet (DRAFT, not approved for pilot)\n\n';
md += `Generated by \`tests/i18n/build-review.js\` from the catalog in \`index.html\` and \`review-meta.json\`. ${rows.length} strings; ${flagged.length} flagged.\n\n`;
md += '**Spanish is not approved for pilot until a native speaker who knows restaurant kitchens has reviewed it.** Reviewer decisions are collected on the review page; this file is the reference copy.\n\n';
md += '## Intentionally untranslated (do not translate in this pass)\n\n| Data | Example | Why |\n|---|---|---|\n' + UNTRANSLATED.map(u => `| ${u.join(' | ')} |`).join('\n') + '\n\n';
const table = list => '| English | Current Spanish | Where it appears | Operational meaning | Review concern | Reviewer-approved Spanish |\n|---|---|---|---|---|---|\n'
  + list.map(r => `| ${cell(r.en)} | ${cell(r.es)} | ${cell(r.where)} | ${cell(r.meaning)} | ${cell((UNRESOLVED.includes(r.key) ? 'UNRESOLVED — requires approval. ' : '') + (r.concern || ''))} | |`).join('\n') + '\n\n';
md += `## Flagged for review (${flagged.length})\n\n` + table(flagged);
for (const [g, label] of GROUPS) {
  const list = rows.filter(r => !r.concern && r.group === g);
  if (list.length) md += `## ${label} (${list.length})\n\n` + table(list);
}
fs.writeFileSync(path.join(__dirname, 'KITCHEN_STRINGS_EN_ES.md'), md);

// ── Review page ────────────────────────────────────────────────────────────────────────────────
const out = process.argv[2];
if (out) {
  const tpl = fs.readFileSync(path.join(__dirname, 'review-page.template.html'), 'utf8');
  const data = { rows, flagged: flagged.map(r => r.key), unresolved: UNRESOLVED, groups: GROUPS, untranslated: UNTRANSLATED,
    generated: new Date().toISOString().slice(0, 10) };
  fs.writeFileSync(out, tpl.replace('/*__DATA__*/null', JSON.stringify(data).replace(/</g, '\\u003c')));
}
console.log(`review material: ${rows.length} strings, ${flagged.length} flagged${out ? ', page → ' + out : ''}`);
